[package]
name = "merge-configs"
version = "0.1.0"
authors = ["Yukun Guo <gyk.net@gmail.com>"]
edition = "2018"

[dependencies]
config = "0.9"
failure = "0.1"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
serde_derive = "1.0"
