[package]
name = "json-in-redis"
version = "0.1.0"
authors = ["Yukun Guo <gyk.net@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
redis-async = "0.6"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "0.2", features = ["macros"] }
